apiVersion: v1
kind: ConfigMap
metadata:
  name: news-app-api-config
  namespace: news-app-api
  annotations:
    argocd.argoproj.io/sync-wave: "0"
data:
  NEWS_API_URL: "https://newsapi.org/v2/everything"
