apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patchesStrategicMerge:
  - values.yaml
  - ingress-patch.yaml
  - configmap-patch.yaml

namespace: news-app-ui
namePrefix: staging-
