apiVersion: apps/v1
kind: Deployment
metadata:
  name: news-app-ui
  namespace: news-app-ui
spec:
  template:
    spec:
      containers:
        - name: news-app-ui
          image: khumo/news-app:v2.5.5
