apiVersion: apps/v1
kind: Deployment
metadata:
  name: news-app-api
  namespace: news-app-api
spec:
  template:
    spec:
      containers:
        - name: news-app-api
          image: khumo/news-api:v1.0.4
