apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: static-auth
  namespace: news-app-api
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  # vaultConnection: default
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: vso-role
    serviceAccount: default
    audiences:
      - vault
    tokenExpirationSeconds: 600 # 10 minutes
