apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: news-app-ui-ingressroute-certificate
  namespace: news-app-ui
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  secretName: news-app-ui-certificate-secret
  issuerRef:
    name: cloudflare-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - news-app-ui.dev.khumo.cloud
