apiVersion: apps/v1
kind: Deployment
metadata:
  name: news-app-ui
  namespace: news-app-ui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: news-app-ui
  template:
    metadata:
      labels:
        app: news-app-ui
    spec:
      containers:
        - name: news-app-ui
          image: khumo/news-app:v2.5.5
          ports:
            - containerPort: 80
          env:
            - name: APP_API_URL
              valueFrom:
                configMapKeyRef:
                  name: news-app-ui-config
                  key: APP_API_URL
            - name: APP_API_KEY
              valueFrom:
                secretKeyRef:
                  name: news-app
                  key: APP_API_KEY
      resources: {}
