apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: values.yaml
  - path: configmap-patch.yaml
  - path: ingress-patch.yaml
  - path: kv-secret.yaml

namespace: news-app-ui
# namePrefix: prod-