apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-static-secret-news-app-ui
  namespace: news-app-ui
spec:
  vaultAuthRef: static-auth
  mount: kv-v2
  type: kv-v2
  path: news-app/secret
  refreshAfter: 10s
  rolloutRestartTargets:
  - kind: Deployment
    name: news-app-ui
  destination:
    create: true
    name: news-app