apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: multi-cluster-apps
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/khumozin/argocd-apps.git  # Fixed repoURL (no "s" in "app")
        revision: HEAD
        directories:
          - path: "apps/*/overlays/*"
    - list:
        elements:
          - env: dev
            cluster: https://kubernetes.default.svc
          # - env: staging
          #   cluster: https://staging-cluster.example.com
          # - env: prod
          #   cluster: https://prod-cluster.example.com
  template:
    metadata:
      name: '{{path.components[1]}}-{{env}}'  # Uses app name + env (e.g., "app1-dev")
    spec:
      project: default
      source:
        repoURL: https://github.com/khumozin/argocd-apps.git  # Matches Git generator repoURL
        targetRevision: HEAD
        path: 'apps/{{path.components[1]}}/overlays/{{env}}'  # Path built from Git directory values
      destination:
        server: '{{cluster}}'  # Uses cluster URL from List generator
        namespace: '{{path.components[1]}}'  # Namespace = app name (adjust if needed)
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
