apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev-applications
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/khumozin/argocd-apps
        revision: main
        directories:
          - path: apps/*/overlays/dev
  template:
    metadata:
      name: "{{path.dirname | base}}-dev"
    spec:
      project: default
      source:
        repoURL: https://github.com/khumozin/argocd-apps
        targetRevision: main
        path: "{{path}}"
        # kustomize:
        #   namePrefix: dev-
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{path.dirname | base}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
