apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev-applications
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/khumozin/argocd-apps
        revision: main
        directories:
          - path: apps/*/overlays/dev
  template:
    metadata:
      name: >-
        {{ (index (splitList "/" path.directory) 1 | lower | replace "_" "-" | regexReplaceAll "[^a-z0-9-.]" "-" | regexReplaceAll "-+" "-" | trimSuffix "-" | trimPrefix "-") }}
    spec:
      project: default
      source:
        repoURL: https://github.com/khumozin/argocd-apps
        targetRevision: main
        path: "{{path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: >-
          {{ (index (splitList "/" path.directory) 1 | lower | replace "_" "-" | regexReplaceAll "[^a-z0-9-.]" "-" | regexReplaceAll "-+" "-" | trimSuffix "-" | trimPrefix "-") }}
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
