apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - vault-auth.yaml
  - kv-secret.yaml

patches:
  - path: values.yaml
  - path: configmap-patch.yaml
  - path: ingress-patch.yaml
  - path: replicas-patch.yaml

namespace: news-app-api
# namePrefix: staging-
